name: Build Flutter APK

on:
  push:
    branches:
      - main
    paths:
      - 'mobile/**' # Solo ejecutar si hay cambios en la app móvil

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Clonar repositorio
        uses: actions/checkout@v4

      - name: ⚙️ Configurar Java (Requerido por Android)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 🐦 Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: 📥 Instalar dependencias
        working-directory: mobile
        run: flutter pub get

      - name: 🔐 Decodificar Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks
        working-directory: mobile

      - name: 🔨 Compilar APK
        working-directory: mobile
        env:
          KEYSTORE_PATH: "upload-keystore.jks"
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: flutter build apk --release

      - name: 🔍 Obtener versión de pubspec
        id: get_version
        working-directory: mobile
        run: |
          VERSION=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2)
          echo "APP_VERSION=v$VERSION" >> $GITHUB_ENV

      - name: 🚀 Publicar APK en GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.APP_VERSION }}
          name: "Actualización ${{ env.APP_VERSION }}"
          files: mobile/build/app/outputs/flutter-apk/app-release.apk
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
